import 'dart:io';
import 'package:telegram_login/telegram_login.dart';
import 'debug_service.dart';

// Single OAuth client ID for the entire app (from Telegram Login Widget).
const String _clientId           = '8966637225';
// Native app redirect URIs — each ID embedded in the URL is generated by
// Telegram when registering the native app, it is NOT the OAuth client ID.
const String _iosRedirectUri     = 'https://app3555230600-login.tg.dev';
const String _androidRedirectUri = 'https://app258425099-login.tg.dev/tglogin';

final _log = DebugService.talker;

class TelegramAuthService {
  static final _telegramLogin = TelegramLogin();

  /// Initiates the native Telegram OAuth 2.0 flow and returns the OIDC
  /// id_token JWT on success, or null if the user cancelled.
  /// Throws on unexpected errors.
  static Future<String?> authenticate() async {
    final platform = Platform.isIOS
        ? 'iOS'
        : (Platform.isAndroid ? 'Android' : 'other');
    final redirectUri = Platform.isIOS ? _iosRedirectUri : _androidRedirectUri;
    // NOTE: 'openid' is required for the token endpoint to return an id_token.
    // Without it Telegram's /token responds without id_token and the native
    // SDK throws requestFailed('Unexpected token response').
    const scopes = ['openid', 'profile', 'phone'];

    _log.info(
      '[TG][native] authenticate() start · platform=$platform '
      'clientId=$_clientId redirectUri=$redirectUri scopes=$scopes',
    );

    // ── Step 1: configure the native SDK ──────────────────────────────────
    try {
      await _telegramLogin.configure(
        TelegramLoginConfiguration(
          clientId: _clientId,
          redirectUri: redirectUri,
          scopes: scopes,
        ),
      );
      _log.info(
        '[TG][native] configure() OK · isConfigured=${_telegramLogin.isConfigured}',
      );
    } catch (e, st) {
      _log.error('[TG][native] configure() failed', e, st);
      rethrow;
    }

    // ── Step 2: run the native OAuth flow ─────────────────────────────────
    _log.info('[TG][native] login() started — awaiting native OAuth flow…');

    try {
      final result = await _telegramLogin.login();
      final token = result.idToken;
      final preview = token.length > 12 ? '${token.substring(0, 12)}…' : token;
      _log.info(
        '[TG][native] login() success · idToken=${token.length} chars ($preview)',
      );
      if (token.isEmpty) {
        _log.warning('[TG][native] idToken is EMPTY — backend will reject it');
      }
      return token;
    } on TelegramLoginError catch (e, st) {
      if (e.code == TelegramLoginErrorCode.cancelled) {
        _log.info('[TG][native] login() cancelled by user');
        return null;
      }
      _log.error(
        '[TG][native] login() TelegramLoginError [${e.code}]: ${e.message}',
        e,
        st,
      );
      throw Exception('Telegram auth error [${e.code}]: ${e.message}');
    } catch (e, st) {
      _log.error('[TG][native] login() unexpected error', e, st);
      rethrow;
    }
  }
}
